### ISSUE TITLE
Model fails on learning nice

### ISSUE THREAD

**Issue by neubig** [jxhe/struct-learning-with-flow#3]
Hi! I'm trying to run the code, and managed to train the Gaussian to completion effectively, but then am encountering a problem when I actually try to train the structured flow model (using the stable version PyTorch 1.1). The error is below, any pointers about how to debug?

    Traceback (most recent call last):
      File "markov_flow_train.py", line 214, in <module>
        main(parse_args)
      File "markov_flow_train.py", line 132, in main
        model.init_params(init_seed)
      File "/projects/ogma2/users/gneubig/work/struct-learning-with-flow/modules/markov_flow_model.py", line 83, in init_params
        sents, _ = self.transform(sents)
      File "/projects/ogma2/users/gneubig/work/struct-learning-with-flow/modules/markov_flow_model.py", line 115, in transform
        x, jacobian_loss_new = self.nice_layer(x)
      File "/home/gneubig/anaconda3/envs/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
        result = self.forward(*input, **kwargs)
      File "/projects/ogma2/users/gneubig/work/struct-learning-with-flow/modules/projection.py", line 100, in forward
        h = torch.cat((h1, h2 + getattr(self, name)(h1)), dim=-1)
      File "/home/gneubig/anaconda3/envs/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
        result = self.forward(*input, **kwargs)
      File "/projects/ogma2/users/gneubig/work/struct-learning-with-flow/modules/projection.py", line 44, in forward
        h = self.in_layer(input)
      File "/home/gneubig/anaconda3/envs/python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/gneubig/anaconda3/envs/python3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 92, in forward
        return F.linear(input, self.weight, self.bias)
      File "/home/gneubig/anaconda3/envs/python3/lib/python3.7/site-packages/torch/nn/functional.py", line 1408, in linear
        output = input.matmul(weight.t())
    RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:259

Here's how I created the environment, if that's useful:

    conda create --name python3 python=3
    source activate python3
    conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
    conda install scikit-learn nltk

**Comment by jxhe** [comment]
Hi Graham,

I can't reproduce the error with your environment. What GPU are you using ? If it is 2080 Ti, you might need CUDA 10 instead of 9. (I've seen some similar issues from Google but not sure)

**Comment by neubig** [comment]
OK, thanks. It is indeed 2080 Ti, and CUDA 9.0. I'll try with 10 and get back to you.

**Comment by neubig** [comment]
Fixing the CUDA version indeed fixed the problem! Here is an environment creation command that worked.

    conda create --name python3 python=3
    source activate python3
    conda install pytorch torchvision cudatoolkit=10 -c pytorch
    conda install scikit-learn nltk

Thanks!
